# Preparing the data set
## AIM:
- We wish to make a dataset for the neural network to learn.
- In the dataset we will be having a trinng data set and another validation data set.

In [33]:
# Requied libraries
import numpy as np
import torch
from torch.utils.data import Dataset,DataLoader

# One dimensional function
def myfunc(x):
    y = x * torch.sin(x)
    return y

# decide the x domain
xll = 0
xul = 1

# decide the number of training data
n_total = 11
n_train = 10
n_valid = n_total-n_train

# x and y values
x_values = torch.unsqueeze(torch.tensor(np.linspace(xll,xul,n_total),dtype=torch.float32),1)
y_values = myfunc(x_values)

# Defining training and validation indices
randomize_index = torch.randperm(n_total)
train_index = randomize_index[:n_train]
valid_index = randomize_index[n_train:n_total]

# Definig training data
x_train = x_values[train_index]
y_train = y_values[train_index]

# Defining validation data
x_valid = x_values[valid_index]
y_valid = y_values[valid_index]

# Defining CustomDataset class
class CustomDataset(Dataset):
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def __len__(self):
        return len(self.x)
    def __getitem__(self,index):
        x_index = self.x[index]
        y_index = self.y[index]
        return (x_index,y_index)

# training data set
data_train = CustomDataset(x_train,y_train)

# Using data-loader
dataloader_train = DataLoader(data_train, batch_size=2)
for inputs,outputs in dataloader_train:
    print(f"{inputs}:{outputs}")


tensor([[0.6000],
        [0.5000]]):tensor([[0.3388],
        [0.2397]])
tensor([[1.],
        [0.]]):tensor([[0.8415],
        [0.0000]])
tensor([[0.1000],
        [0.8000]]):tensor([[0.0100],
        [0.5739]])
tensor([[0.7000],
        [0.9000]]):tensor([[0.4510],
        [0.7050]])
tensor([[0.2000],
        [0.4000]]):tensor([[0.0397],
        [0.1558]])
